version: '3.3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongodb
 
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      args:
      - VUE_APP_TITLE=Docker Application
      - VUE_APP_API_BACKEND=http:\\localhost:8000
    ports:
      - 8080:80
 
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    restart: unless-stopped
